<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>9.0</LangVersion>
    <DefineConstants>$(DefineConstants);OPENMASU_APPLOVIN_MAX;UNITY_EDITOR</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\com.openmasu.sdk\Runtime\*.cs" Link="Runtime\%(Filename)%(Extension)" />
    <Compile Include="..\com.openmasu.sdk\Editor\OpenMasuIOSPostprocessor.cs" Link="Editor\OpenMasuIOSPostprocessor.cs" />
  </ItemGroup>
</Project>
