import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { compile, type JSONSchema } from "json-schema-to-typescript";

const root = process.cwd();
const schemaRoot = join(root, "schemas");
const outputPath = join(root, "tools", "generated", "contract-types.ts");
const artifacts = {
  raw_records: "raw-record.schema.json",
  deliveries: "event-delivery.schema.json",
  logical_events: "logical-event.schema.json",
  corrections: "correction.schema.json",
  privacy_requests: "privacy-request.schema.json",
  privacy_tombstones: "privacy-tombstone.schema.json",
  attributions: "attribution-result.schema.json",
  metric_runs: "metric-run.schema.json",
  fraud_decisions: "fraud-decision.schema.json",
  rejections: "rejection.schema.json",
  reconciliation: "reconciliation-result.schema.json",
} as const;

const schema: JSONSchema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  title: "Open MMP Evaluation Output v0.1",
  type: "object",
  additionalProperties: false,
  required: Object.keys(artifacts),
  properties: Object.fromEntries(
    Object.entries(artifacts).map(([name, path]) => [name, {
      type: "array",
      items: { $ref: path },
    }]),
  ),
};

const generated = await compile(schema, "EvaluationOutput", {
  cwd: schemaRoot,
  bannerComment: "/* This file is generated by npm run generate:types. Do not edit it directly. */",
  additionalProperties: false,
  declareExternallyReferenced: true,
  enableConstEnums: false,
  ignoreMinAndMaxItems: true,
  unknownAny: true,
  style: {
    bracketSpacing: true,
    printWidth: 120,
    semi: true,
    singleQuote: false,
    tabWidth: 2,
    trailingComma: "all",
    useTabs: false,
  },
});

mkdirSync(join(root, "tools", "generated"), { recursive: true });
writeFileSync(outputPath, generated, "utf8");
console.log(`Generated ${Object.keys(artifacts).length} contract artifact types at ${outputPath}`);
