import type { AttributionReport, AttributionQuery } from "../attribution-reporting.js";
import { escapeHtml as escape } from "./render.js";

export function renderAttributionReport(appId: string, report?: AttributionReport): string {
  const app = encodeURIComponent(appId), query = report?.selection;
  const input = (key: keyof AttributionQuery, label: string, type = "text") => `<label>${label} <input type="${type}" name="${key}" value="${escape(query?.[key] ?? "")}" required></label>`;
  const form = `<form method="get" action="/dashboard/apps/${app}/attribution">${input("date_from", "Install cohort from (inclusive)", "date")}${input("date_to", "Install cohort to (exclusive)", "date")}<label>Time zone <select name="time_zone"><option value="UTC"${query?.time_zone === "UTC" ? " selected" : ""}>UTC</option><option value="Asia/Tokyo"${query?.time_zone === "Asia/Tokyo" ? " selected" : ""}>Asia/Tokyo</option></select></label>${input("watermark_at_most", "Fixed UTC receive/decision cutoff")}<button type="submit">Read recorded reasons</button></form>`;
  const result = report ? `<section><h2>Recorded installation attribution</h2><dl>${Object.entries(report.selection).map(([key, value]) => `<dt>${escape(key)}</dt><dd>${escape(value)}</dd>`).join("")}<dt>Population</dt><dd>${escape(report.population)}</dd><dt>Current privacy</dt><dd>${escape(report.privacy)}</dd><dt>Selection</dt><dd>${escape(report.selection_rule)}</dd><dt>Installations in denominator</dt><dd data-attribution-denominator="${escape(report.denominator)}">${escape(report.denominator)}</dd></dl><table><caption>One selected stored decision per retained installation, not deliveries</caption><thead><tr><th scope="col">Recorded</th><th scope="col">Status</th><th scope="col">Method</th><th scope="col">Stored reason</th><th scope="col">Installations</th></tr></thead><tbody>${report.data.map(row => `<tr data-attribution-count="${escape(row.count)}"><th scope="row">${escape(row.recording_state)}</th><td>${escape(row.status ?? "—")}</td><td>${escape(row.method ?? "—")}</td><td>${escape(row.reason_code ?? "—")}</td><td>${escape(row.count)}</td></tr>`).join("")}</tbody></table>${report.denominator === "0" ? "<p>No retained accepted installations match this selection.</p>" : ""}<p><a href="/v1/admin/apps/${app}/attribution?${escape(new URLSearchParams({ date_from: query!.date_from, date_to: query!.date_to, time_zone: query!.time_zone, watermark_at_most: query!.watermark_at_most }).toString())}">Same-selection API URL (requires a bearer key, not this session)</a></p></section>` : "<p>Select a cohort period and fixed cutoff. No counts are calculated until the selection is complete.</p>";
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>OpenMasu attribution reasons</title><link rel="stylesheet" href="/dashboard/app.css"></head><body><main><h1>Attribution reason counts</h1><p><a href="/dashboard/apps/${app}">Back to cohort reports and separate Apple aggregate series</a> · <a href="/dashboard/apps/${app}/tracking-links">First-party engagement links</a></p>${form}${result}<p>The denominator is accepted installation-level acquisition, not aggregate postbacks or deep-link re-engagement. Latest eligible decisions are selected as of the cutoff; later decisions and evidence are excluded. A missing decision is not_recorded, not organic. Current redaction/purge removes an installation even at an earlier cutoff.</p><p>These are recorded reasons, not a new attribution calculation or inferred diagnosis. Unavailable referrers do not prove fraud, a broken SDK or media fault. Counts do not certify upstream completeness. The period is limited to 366 days and 100,000 retained installations; oversized or unavailable queries fail without partial counts.</p></main></body></html>`;
}
